### ISSUE TITLE
Unhandled fault after ICMP echo request

### ISSUE THREAD

**Issue by mgalemin** [mgalemin/buildroot#12]
Pre conditions:
Beagleboard-xM has IP address configured.

Execution:
Send ICMP request from external host (i.e. ping the Beagleboard-xM).

Expected result:
Beagleboard-xM responds to ICMP requests.

Result:
Linux kernel throws "Unhandled fault" after receiving ICMP echo request. Please see full log below.

[root@buildroot ~]# [   25.104858] Unhandled fault: alignment exception (0x001) at 0xde4d002a
[   25.111846] Internal error: : 1 [#1] SMP
[   25.115905] last sysfs file: 
[   25.119018] Modules linked in:
[   25.122192] CPU: 0    Not tainted  (2.6.39.1-mg00 #1)
[   25.127441] PC is at icmp_echo+0x58/0xb4
[   25.131530] LR is at icmp_rcv+0x2f8/0x398
[   25.135681] pc : [<c0405a6c>]    lr : [<c0406228>]    psr: 60000113
[   25.135681] sp : c0629de8  ip : 00000001  fp : 00000000
[   25.147644] r10: dec7f8c0  r9 : c1014f08  r8 : c1014f14
[   25.153076] r7 : 00000008  r6 : de475080  r5 : de4d0016  r4 : dec7f8c0
[   25.159851] r3 : 00000000  r2 : c0629df4  r1 : de4d002a  r0 : dec7f8c0
[   25.166625] Flags: nZCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment kernel
[   25.174224] Control: 10c5387d  Table: 9e4e4019  DAC: 00000017
[   25.180206] Process swapper (pid: 0, stack limit = 0xc06282f8)
[   25.186279] Stack: (0xc0629de8 to 0xc062a000)
[   25.190826] 9de0:                   0201a8c0 a0000113 dec7f8c0 de475080 00000000 00000000
[   25.199310] 9e00: 00000000 c06840c4 00000000 00000002 c1014f08 60000113 00000001 c00c67e4
[   25.207824] 9e20: 00000001 00000000 00000000 c03dca28 00000000 00000000 fe020020 00000000
[   25.216339] 9e40: dec7f8c0 c0406228 c0405f30 c04a2e78 de4d0016 dec7f8c0 00000008 c03dcb1c
[   25.224853] 9e60: 00000001 00000000 c03dca28 deffe000 00000000 de4d0016 dec7f8c0 c03dc998
[   25.233337] 9e80: deffe000 00000001 c063ef98 deffe000 c063ea74 00000000 00000008 c03bc1bc
[   25.241851] 9ea0: 00000001 00000000 c03bbebc 00000000 00000040 c1014f14 00000000 dec7f8c0
[   25.250366] 9ec0: c03bc2b4 c063ea94 00000001 c1014fb4 c1014f00 00000000 00000001 c03bc2c0
[   25.258850] 9ee0: c03bc22c c1014fb4 c1014f00 c0628000 00000001 0000012c 00000040 c03bcbf8
[   25.267364] 9f00: c062a04c ffff7698 00000000 00000001 c062a04c c0628000 00000100 00000009
[   25.275878] 9f20: 413fc082 00000003 00000000 c009c120 c062db4c 00000448 00000000 c0628000
[   25.284393] 9f40: 00000000 c1010120 c0641f3c 80000000 413fc082 00000000 00000000 c009c6b4
[   25.292877] 9f60: 0000004d c005208c c0640710 ffffffff fa200000 c046335c 00000001 00000004
[   25.301391] 9f80: c0629fb0 05e35d23 c063e47c c0036e6c c1010120 c0641f3c 80000000 413fc082
[   25.309906] 9fa0: 00000000 00000000 00000000 c0629fc0 c00c70a8 c006e91c 20000013 ffffffff
[   25.318389] 9fc0: c063e47c c0036e6c c1010120 c005d1e8 00000000 c0008a44 c000849c 0000060a
[   25.326904] 9fe0: 80000100 c0036e6c 10c53c7d c063d8dc c0036e68 8000803c 00000000 00000000
[   25.335418] [<c0405a6c>](icmp_echo+0x58/0xb4) from [<c0406228>](icmp_rcv+0x2f8/0x398)
[   25.343780] [<c0406228>](icmp_rcv+0x2f8/0x398) from [<c03dcb1c>](ip_local_deliver_finish+0x128/0x354)
[   25.353546] [<c03dcb1c>](ip_local_deliver_finish+0x128/0x354) from [<c03dc998>](ip_rcv_finish+0x4d4/0x530)
[   25.363769] [<c03dc998>](ip_rcv_finish+0x4d4/0x530) from [<c03bc1bc>](__netif_receive_skb+0x390/0x400)
[   25.373626] [<c03bc1bc>](__netif_receive_skb+0x390/0x400) from [<c03bc2c0>](process_backlog+0x94/0x178)
[   25.383575] [<c03bc2c0>](process_backlog+0x94/0x178) from [<c03bcbf8>](net_rx_action+0x74/0x218)
[   25.392913] [<c03bcbf8>](net_rx_action+0x74/0x218) from [<c009c120>](__do_softirq+0xfc/0x208)
[   25.401977] [<c009c120>](__do_softirq+0xfc/0x208) from [<c009c6b4>](irq_exit+0x54/0x98)
[   25.410461] [<c009c6b4>](irq_exit+0x54/0x98) from [<c005208c>](asm_do_IRQ+0x8c/0xc8)
[   25.418731] [<c005208c>](asm_do_IRQ+0x8c/0xc8) from [<c046335c>](__irq_svc+0x3c/0x120)
[   25.427124] Exception stack(0xc0629f78 to 0xc0629fc0)
[   25.432373] 9f60:                                                       00000001 00000004
[   25.440887] 9f80: c0629fb0 05e35d23 c063e47c c0036e6c c1010120 c0641f3c 80000000 413fc082
[   25.449401] 9fa0: 00000000 00000000 00000000 c0629fc0 c00c70a8 c006e91c 20000013 ffffffff
[   25.457916] [<c046335c>](__irq_svc+0x3c/0x120) from [<c006e91c>](omap3_pm_idle+0x194/0x1a4)
[   25.466796] [<c006e91c>](omap3_pm_idle+0x194/0x1a4) from [<c005d1e8>](cpu_idle+0x90/0xf8)
[   25.475463] [<c005d1e8>](cpu_idle+0x90/0xf8) from [<c0008a44>](start_kernel+0x298/0x2ec)
[   25.484069] [<c0008a44>](start_kernel+0x298/0x2ec) from [<8000803c>](0x8000803c)
[   25.491943] Code: e3530000 1a000012 e5941080 e28d200c (e8910003) 
[   25.498321] ---[ end trace f2aad9aa0c3f80a2 ]---
[   25.503143] Kernel panic - not syncing: Fatal exception in interrupt

**Comment by uolli** [comment]
Hi Max, 

checking here - http://git.mansr.com/?p=linux-xm;a=commitdiff;h=d204c927d856cbe7d7fa90b0703d1ab5b7c6be80 for how to fix this issue, i have tested, it working. 

Li

**Comment by mgalemin** [comment]
Fixed.
