### ISSUE TITLE
kernel loading problem on beagleboard xM Rev A

### ISSUE THREAD

**Issue by ivannaz** [mgalemin/buildroot#23]
I tried the MLO / u-boot.img / uEnv.txt / uImage from https://github.com/downloads/MaxGalemin/buildroot/

On beagle xM rev. A, I got a Kernel Panic: http://pastebin.com/FJcHxy72

Compiling locally, doing:
make beagle_xm_defconfig
make menuconfig
- enable building gcc 4.5 locally,
- disable monit (it fails compiling)
- enabled, if not enabled yet, dropbear.

and then make.

The generated image dies on booting in a different step: http://pastebin.com/nqBNvdSZ
The point it stops is not constant, though. It freezed twice on the "ThumbEE CPU extension supported"

This image worked perfectly on a xM rev. C, though.

**Comment by mgalemin** [comment]
Thanks for the information. Yep, there is a bug in configuration of Monit + uClibc, I'll fix it. A couple of questions:
1. You've mentioned that you are running images on BB-xM version A, could you please provide me with the exact version number (I'm working with A3)?
2. Could you please try to compile images using Codesourcery 2011.09 as this is the version I'm using now (I haven't done much testing with another versions of GCC, sorry)? You can download it for free after registration on Mentor Graphics website: http://www.mentor.com/embedded-software/sourcery-tools/sourcery-codebench/editions/lite-edition/
3. Are you sure you are using "beagle_xm_defconfig" but not "beagle_xm_full_defconfig" as basic version of defconfig does'n have Monit package.

Thanks.

**Comment by ivannaz** [comment]
I would like to update the yesterday answers:

1 - I am working with A3 too,
2 - I compiled the tests now with CS2911.09, with the same result.
3 - (CHANGED) First I used "beagle_xm_full_defconfig". I recompiled everything with "beagle_xm_defconfig" and CS2011.09, but still doing make menuconfig and adding: libjpeg, opencv and dropbear.

But this issue is somehow related to hardware - possibly mine particular hardware. What I found today is that:
- By booting the rev. A3 by cycling the power, the A3 does complete the boot if the board is cold (if I leave it off time enough or if I cool it with compressed air). This was tested many times and always work.
- After one or two boots, the A3 will not boot again by cycling power. I tested this many times, never worked - but sometimes I get kernel panic, sometimes just freeze. Oddly, the Angstrom kernels still work.
- If, instead of cycling power, I press "reset" button, the board does boot! Even hot. I tested this many times, mixing with the power cycling test.
- Otherwise this board did not show any other hardware instability.

So what we have here is that this 3.2.8 kernel is somehow sensitive to the boot via power cycling in the rev. A3 beagleboards, but still boots if reset is pressed. 

Odd. If your board do not show this, I suppose I have some hardware issue in this particular beagle, triggered by something kernel 3.2.8 does (or does not) on boot.

**Comment by mgalemin** [comment]
Yep, sometimes I have the same results after cold power cycling. Kernel freezes in arch/arm/mach-opam2/pm34xx.c at omap3_iva_idle() function after clearing the IVA2 module reset with mpurate=1000:

omap2_prm_write_mod_reg(0, OMAP3430_IVA2_MOD, OMAP2_RM_RSTCTRL);

Needs more investigation...

P.S. It seems that mpurate=800 works quite reliably, so the problem is in 1 GHz configuration.

**Comment by mgalemin** [comment]
commit c366cf7ed5f98bba242269a694a9b7904e249ec4
Author: Max Galemin maksim.galemin@gmail.com
Date:   Fri Mar 9 00:12:30 2012 +1100

```
Issue 23: kernel loading problem on beagleboard xM Rev A

1. Added Linux kernel patch for fixing issue with kernel panics and freezes on
Beagleboard-xM Rev. A3 with "mpurate=1000" kernel boot parameter.
```

A       board/beagleboard/xm/kernel-patches/linux-0005-Put-the-IVA2-DPLL-in-stop-mode-before-un-reset-IVA2.patch

**Comment by mgalemin** [comment]
commit 26f7446f15d60ec4880866f6f0ed847fe0a8a0eb
Merge: 7e18b75 c366cf7
Author: Max Galemin maksim.galemin@gmail.com
Date:   Fri Mar 9 00:16:21 2012 +1100

```
Merge branch 'Issue-23_kernel_loading_problem_on_beagleboard_xM_Rev_A' into develop
```

**Comment by mgalemin** [comment]
Bumped patch release 2012.02-mg01.2.

ivannaz, could you please confirm that issue resolved? Thanks.

**Comment by ivannaz** [comment]
Yes! The kernel boots reliably now.

Thank you.
