### ISSUE TITLE
Monit package can't be built with uClibc 

### ISSUE THREAD

**Issue by mgalemin** [mgalemin/buildroot#24]
Monit package can't be built with Buildroot internal toolchain (4.5/4.6) and uClibc.

**Comment by ivannaz** [comment]
Additionally, 4.6.2 can not compile openssl due to the "can't resolve '.LC4'" bug: http://gcc.gnu.org/bugzilla/show_bug.cgi?id=48308, unless you manually change the optimization to -O1.

Perhaps by 4.6.4 we will have this issue closed.

**Comment by mgalemin** [comment]
commit b75e67b4909d31025ae2bbf6b6dd442fb3fc7238
Author: Max Galemin maksim.galemin@gmail.com
Date:   Sun Mar 11 14:12:44 2012 +1100

```
Issue 24: Monit package can't be built with uClibc

1. Added extra dependencies for monit package. Monit can be compiled against libc with getloadavg support only.
```

M       package/monit/Config.in

**Comment by mgalemin** [comment]
commit 769dc5f4c39edf8b8d4c228fefb4251696d3bcb9
Author: Max Galemin maksim.galemin@gmail.com
Date:   Mon Mar 12 20:53:01 2012 +1100

```
Issue 24: Monit package can't be built with uClibc

1. Changed default buildroot internal toolchain to GCC 4.6.x;
2. Changed GCC version from 4.6.2 to 4.6.3.
```

M       toolchain/gcc/Config.in

**Comment by mgalemin** [comment]
commit 5a7b1edfb051aa82d46f05c7adc6c9af27ad7ec1
Merge: 26f7446 769dc5f
Author: Max Galemin maksim.galemin@gmail.com
Date:   Mon Mar 12 20:55:11 2012 +1100

```
Merge branch 'Issue-24_Monit_package_cant_be_built_with_uClibc' into develop
```
