### ISSUE TITLE
misc-utils missing header file.

### ISSUE THREAD

**Issue by lewuskip** [mgalemin/buildroot#26]
Hi all,

I have just check out the repository and tried to compile using make beagle_xm_full_defconfig I got following problem, any idea ?
Making all in login-utils
make[3]: Entering directory `/project/beagle/buildroot/output/build/host-util-linux-2.20/login-utils'
  CC     checktty_test-checktty.o
  CC     islocal_test-islocal.o
  CCLD   islocal_test
  CCLD   checktty_test
make[3]: Leaving directory`/project/beagle/buildroot/output/build/host-util-linux-2.20/login-utils'
Making all in misc-utils
make[3]: Entering directory `/project/beagle/buildroot/output/build/host-util-linux-2.20/misc-utils'
  CC     cal.o
  CC     mbsalign.o
cal.c:82:71: error: term.h: No such file or directory
cal.c: In function ‘my_setupterm’:
cal.c:86: warning: implicit declaration of function ‘setupterm’
make[3]: *** [cal.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory`/project/beagle/buildroot/output/build/host-util-linux-2.20/misc-utils'
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory `/project/beagle/buildroot/output/build/host-util-linux-2.20'
make[1]: *** [all] Error 2
make[1]: Leaving directory`/project/beagle/buildroot/output/build/host-util-linux-2.20'
make: **\* [/project/beagle/buildroot/output/build/host-util-linux-2.20/.stamp_built] Error 2

I will start investigate that but maybe somebody hit the problem already and got quick solution.

**Comment by mgalemin** [comment]
See comments for the following blog post:

http://blog.galemin.com/2012/03/buildroot-2012-02-for-beagleboard-xm-with-li-5m03-mt9p031-camera-support/
