### ISSUE TITLE
media-ctl compiling problem

### ISSUE THREAD

**Issue by lewuskip** [mgalemin/buildroot#27]
I got an issue during compiling media-ctl. I have run make beagle_xm_full_defconfig first and then make.
I got the recent snapshot from buildroot git repos.

> > > media-ctl 36a1357c9c879092fe2e36c82187f1d35b1efe13 Configuring
> > > (cd /project/beagle/buildroot/output/build/media-ctl-36a1357c9c879092fe2e36c82187f1d35b1efe13/ && rm -rf config.cache && PATH="/project/beagle/buildroot/output/host/bin:/project/beagle/buildroot/output/host/usr/bin:/project/beagle/buildroot/output/host/usr/sbin/:/opt/CodeSourcery/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games" AR="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-ar" AS="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-as" LD="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-ld" NM="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-nm" CC="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-gcc" GCC="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-gcc" CPP="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-cpp" CXX="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-g++" FC="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-gfortran" RANLIB="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-ranlib" STRIP="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-strip" OBJCOPY="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-objcopy" OBJDUMP="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-objdump" AR_FOR_BUILD="/usr/bin/ar" AS_FOR_BUILD="/usr/bin/as" CC_FOR_BUILD="/usr/bin/gcc" GCC_FOR_BUILD="/usr/bin/gcc" CXX_FOR_BUILD="/usr/bin/g++" FC_FOR_BUILD="/usr/bin/ld" LD_FOR_BUILD="/usr/bin/ld" CFLAGS_FOR_BUILD="-O2 -I/project/beagle/buildroot/output/host/include -I/project/beagle/buildroot/output/host/usr/include" CXXFLAGS_FOR_BUILD="-I/project/beagle/buildroot/output/host/include -I/project/beagle/buildroot/output/host/usr/include" LDFLAGS_FOR_BUILD="-L/project/beagle/buildroot/output/host/lib -L/project/beagle/buildroot/output/host/usr/lib -Wl,-rpath,/project/beagle/buildroot/output/host/usr/lib" FCFLAGS_FOR_BUILD="" DEFAULT_ASSEMBLER="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-as" DEFAULT_LINKER="/project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-ld" CFLAGS=" -pipe -mfpu=neon -ftree-vectorize -mfloat-abi=softfp -Os  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64" CXXFLAGS=" -pipe -mfpu=neon -ftree-vectorize -mfloat-abi=softfp -Os  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64" LDFLAGS="" FCFLAGS="" PKG_CONFIG="/project/beagle/buildroot/output/host/usr/bin/pkg-config" PERLLIB="/project/beagle/buildroot/output/host/usr/lib/perl" STAGING_DIR="/project/beagle/buildroot/output/host/usr/arm-unknown-linux-gnueabi/sysroot" ac_cv_lbl_unaligned_fail=yes ac_cv_func_mmap_fixed_mapped=yes ac_cv_func_memcmp_working=yes ac_cv_have_decl_malloc=yes gl_cv_func_malloc_0_nonnull=yes ac_cv_func_malloc_0_nonnull=yes ac_cv_func_calloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes lt_cv_sys_lib_search_path_spec="" ac_cv_c_bigendian=no  ./configure --target=arm-linux --host=arm-linux --build=i686-pc-linux-gnu --prefix=/usr --exec-prefix=/usr --sysconfdir=/etc --program-prefix="" --disable-gtk-doc    --enable-static --enable-shared  --with-kernel-headers=/project/beagle/buildroot/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include )
> > > configure: WARNING: unrecognized options: --disable-gtk-doc
> > > checking for a BSD-compatible install... /usr/bin/install -c
> > > checking whether build environment is sane... yes
> > > checking for arm-linux-strip... /project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-strip
> > > checking for a thread-safe mkdir -p... /bin/mkdir -p
> > > checking for gawk... gawk
> > > checking whether make sets $(MAKE)... yes
> > > checking for arm-linux-gcc... /project/beagle/buildroot/output/host/usr/bin/arm-none-linux-gnueabi-gcc
> > > checking whether the C compiler works... yes

...

checking linux/media.h usability... no
checking linux/media.h presence... no
checking for linux/media.h... no
ERROR: Kernel header file not found or not usable!

**Comment by mgalemin** [comment]
Hi lewuskip,

Try to install "linux-headers" package.

Cheers,
Max.

**Comment by lewuskip** [comment]
Hi Max,

I got a question about these headers. What I can see now linux headers are generated from uclibc with version 2.6.26 and copied into the output/staging/usr/include/linux .
The order of building is uclibc and then linux-3.2.8 sources.
I can add generating linux headers from sources into the build but then it will replace one generated by uclibc and I dont know is will be ok for the rest packages.

Do you know why these headers are missing, is it something missing in your buildroot and should be added or I did something wrong ?

Best,
Piotr

**Comment by mgalemin** [comment]
The same comment. Try to install "linux-headers" on your host machine.

**Comment by akw0088** [comment]
I'm experiencing the same issue: --with-kernel-headers=/home/awright/beagle/buildroot/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include

http://paste2.org/p/2060944

I dont think my host headers should come into play when cross compiling

**Comment by lewuskip** [comment]
Hi akw0088,

My solution was to manually generate kernel-headers from kernel sources and then copied them into the output build.
Works for me however I didn't bother to include it into build  system so I have to do it each time I take fresh copy from the server.

Best,
Piotr

**Comment by akw0088** [comment]
I keep running into media.h found but not usable errors when attempting this. Could you provide me with some shell commands to fix the issue? Thanks for the help! And thanks Galemin for the buildroot as getting the parallel interface to work is a real pain

**Comment by ghost** [comment]
Hi Max,

I have the following problem while building with "make beagle_xm_full_defconfig":

Initialized empty Git repository in /home/tkle/Workspace/Test/buildroot-2012.02/dl/media-ctl-36a1357c9c879092fe2e36c82187f1d35b1efe13/
git.ideasonboard.org[0: 95.142.166.194]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
--2012-08-14 05:48:31--  http://sources.buildroot.net//media-ctl-36a1357c9c879092fe2e36c82187f1d35b1efe13.tar.gz
Resolving sources.buildroot.net... 176.9.16.109
Connecting to sources.buildroot.net|176.9.16.109|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2012-08-14 05:48:32 ERROR 404: Not Found.

make: **\* [/home/tkle/Workspace/Test/buildroot-2012.02/output/build/media-ctl-36a1357c9c879092fe2e36c82187f1d35b1efe13/.stamp_downloaded] Error 1

Could you please give me your idea? Thanks in advance!

Regards,
Pascal

**Comment by ghost** [comment]
Hi all, 

Sorry for my previous question, the problem came from my free public wi-fi, it does not allow to clone.

Thanks again,
Pascal
