### ISSUE TITLE
ethernet (usb0) not working

### ISSUE THREAD

**Issue by lewuskip** [mgalemin/buildroot#28]
Hi Max,

I have managed to build kernel and filesystem using your repos but having problem with ethernet over USB.

ifconfig
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:182 errors:0 dropped:0 overruns:0 frame:0
          TX packets:182 errors:0 dropped:0 overruns:0 B)  TX bytes:19152 (18.7 KiB)

usb0      Link encap:Ethernet  HWaddr 32:FA:DA:3C:96:61  
          inet addr:192.168.1.3  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:11 errors:0 dropped:6 overruns:0 frame:0
          TX packets:144 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2024 (1.9 KiB)  TX bytes:7752 (7.5 KiB)

I ma using static addresses, board is connected to other computer using HUB and third computer running wireshark.
Aparently nothing comming out from the board. I power up the board using USB.

Any sugestion?

thx,
Piotr

**Comment by lewuskip** [comment]
Looks like USB hub works fine, I have connected USB mouse and has been successfully detected by linux, but ethernet still not sending anything.

**Comment by lewuskip** [comment]
More comments :)

I have tested Angstrom demo image and got ourput after lsmod

root@beagleboard:~# lsmod
Module                  Size  Used by
bufferclass_ti          4596  0 
omaplfb                 8749  0 
pvrsrvkm              126503  2 bufferclass_ti,omaplfb
rfcomm                 33484  0 
ircomm_tty             30305  0 
ircomm                 16429  1 ircomm_tty
irda                  162973  2 ircomm_tty,ircomm
ipv6                  249063  8 
hidp                   11193  0 
l2cap                  30104  4 rfcomm,hidp
bluetooth              49221  3 rfcomm,hidp,l2cap
rfkill                 14838  2 bluetooth
minix                  25759  0 
rtc_tw           4451  0 
rtc_core               12535  1 rtc_twl
mt9t112                 9246  0 

First I would expect something like smsc95xx module, second I got nothing when execute it from image generated by buildroot.

**Comment by mgalemin** [comment]
Hi Piotr,

Which Ethernet USB adapter are you using?

**Comment by lewuskip** [comment]
Hi Max,

I am talking about the Etherent on the board (beagleboard-xm revC) which is connected to the one of the USB port on the hub on the board. This is smsc95xx chip. 
I have a strange observation, from the user/software point of view nothing is wrong, I can up the usb0 ehternet interface with static addresses and looks ok. Additionally I see a small amount of packets RX/TX but I dont see anything on the wire using wireshark.

Dont worry bout that now as I will do some more additionally investigation for next few days including testing yout kernel and filessystem provided on your website. 
Unless you got some quick thoughts I can check.

I will put more comments latter this week.

Thx,
Piotr

**Comment by lewuskip** [comment]
Hi Max,

I have tested yout uImage and rootfs full (link for rootfs reduced doeasnt seems to work anymore) and got the same results so looks like I am doing something fundamentaly wrong :)

Once the board is booted I type 
ifconfig usb0 192.168.1.3 netmask 255.255.255.0 up

and expecting that ethernet over usb on the board start to work but then I monitor TX and RX packages using ifconfig and all counters are 0`s.

This is the last lines after dmesg and ifconfig output 

[    5.668940] omap_i2c omap_i2c.1: IRQ (ISR = 0x0004)
[    5.669192] twl_rtc twl_rtc: setting system clock to 2000-01-01 00:00:00 UTC (946684800)
[    5.677979] omap_vout omap_vout: probed for an unknown device
[    5.704321] kjournald starting.  Commit interval 5 seconds
[    5.864771] EXT3-fs (mmcblk0p2): using internal journal
[    5.871072] EXT3-fs (mmcblk0p2): mounted filesystem with ordered data mode
[    5.878627] VFS: Mounted root (ext3 filesystem) on device 179:2.
[    5.890282] devtmpfs: mounted
[    5.894117] Freeing init memory: 340K
[    7.043817] hub 2-0:1.0: hub_suspend
[    7.044769] usb usb2: bus auto-suspend, wakeup 1
[    8.600788] i2c i2c-1: master_xfer[0] W, addr=0x49, len=2
[    8.601009] omap_i2c omap_i2c.1: addr: 0x0049, len: 2, flags: 0x0, stop: 1
[    8.601057] omap_i2c omap_i2c.1: IRQ (ISR = 0x5000)
[    8.601092] omap_i2c omap_i2c.1: IRQ (ISR = 0x0104)
[    8.602811] i2c i2c-1: master_xfer[0] W, addr=0x49, len=2
[    8.602907] omap_i2c omap_i2c.1: addr: 0x0049, len: 2, flags: 0x0, stop: 1
[    8.602956] omap_i2c omap_i2c.1: IRQ (ISR = 0x5000)
[    8.602989] omap_i2c omap_i2c.1: IRQ (ISR = 0x0104)
[   52.830317] usb0: eth_open
[root@beagleboard-xm usr]# ifconfig
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

usb0      Link encap:Ethernet  HWaddr FE:C5:93:80:BB:95  
          inet addr:192.168.1.3  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

Any idea ?

Best regards,
Piotr

**Comment by mgalemin** [comment]
Please try to use eth0 instead of usb0 and update your /etc/network/interfaces with proper network configuration.
