### ISSUE TITLE
 Kernel panic - not syncing: No init found.

### ISSUE THREAD

**Issue by scancool** [mgalemin/buildroot#31]
I'm getting this error, I had tried with both filesystems, how can it be fix? also if this would had work where I would see the image from the camera?

[    5.454199] mt9p031 2-0048: MT9P031 detected at address 0x48  
[    5.507042] smsc95xx 1-2.1:1.0: eth0: register 'smsc95xx' at usb-ehci-omap.02
[    5.526679] clock: disabling unused clocks to save power  
[    5.539587] fbcvt: 1024x768@60: CVT Name - .786M3-R  
[    5.549379] mmc0: host does not support reading read-only switch. assuming w.
[    5.564820] mmc0: new high speed SDHC card at address 1234  
[    5.570953] mmcblk0: mmc0:1234 SA04G 3.68 GiB  
[    5.592075]  mmcblk0: p1 p2  
[    5.600611] Console: switching to colour frame buffer device 128x48  
[    5.626703] regulator_init_complete: VDAC: incomplete constraints, leaving on
[    5.637821] input: gpio-keys as /devices/platform/gpio-keys/input/input1  
[    5.650364] twl_rtc twl_rtc: setting system clock to 2000-01-01 01:52:48 UTC)
[    5.659191] omap_vout omap_vout: probed for an unknown device  
[   12.193068] kjournald starting.  Commit interval 5 seconds  
[   12.610298] EXT3-fs (mmcblk0p2): using internal journal  
[   12.615941] EXT3-fs (mmcblk0p2): recovery complete  
[   12.630266] EXT3-fs (mmcblk0p2): mounted filesystem with ordered data mode  
[   12.637700] VFS: Mounted root (ext3 filesystem) on device 179:2.  
[   12.644960] devtmpfs: error mounting -2  
[   12.649447] Freeing init memory: 340K  
[   12.654081] Kernel panic - not syncing: No init found.  Try passing init= op

**Comment by mgalemin** [comment]
Could you please post here a link to the full serial output after power cycling you board (pastebin please)? Thanks.

**Comment by scancool** [comment]
Thanks for your reply, it works now, I was creating the partition myself and I keep getting kernel panic, then I just burn the img from angstrom site, deleted those file from sd card and added yours and it works now, 
thank you.

**Comment by mgalemin** [comment]
Thanks, issue closed.

**Comment by DanieloDelgado** [comment]
What version of Angstrom did you use? I installed the precompiled images, erased the previous files ones and then paste the new ones. I keep getting this:
[    5.649135] twl_rtc twl_rtc: setting system clock to 2000-01-01 00:00:00 UTC (946684800)
[    5.657987] omap_vout omap_vout: probed for an unknown device
[   10.085189] kjournald starting.  Commit interval 5 seconds
[   10.232155] EXT3-fs (mmcblk0p2): using internal journal
[   10.237803] EXT3-fs (mmcblk0p2): recovery complete
[   10.396453] EXT3-fs (mmcblk0p2): mounted filesystem with ordered data mode
[   10.404029] VFS: Mounted root (ext3 filesystem) on device 179:2.
[   10.411242] devtmpfs: error mounting -2
[   10.415834] Freeing init memory: 340K
[   10.420351] Kernel panic - not syncing: No init found.  Try passing init= option to kernel. See Linux Documentation/init.txt for guidance.
